### ISSUE TITLE
Special Characters Have Invalid Keycodes

### ISSUE THREAD

**Issue by DBJ314** [simon987/Much-Assembly-Required#108]
The keycode values for non-alphanumeric characters tend to be different from the value required to display them. For instance, a period is displayed using the code 0x2f but the code from the key buffer is 0xbf.

**Comment by murkaje** [comment]
You are probably mixing up Keycodes(for input) and ASCII codes(for printing) which are completely different. It does overlap on the 'A'-'Z' region likely because of historic reasons.
In ASCII the code for '.' is 0x2e and the Keycode is 0xbf aka VK_OEM_PERIOD.

Here's a listing of keycodes: https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx

**Comment by DBJ314** [comment]
Ok. That makes sense. Sorry for bringing it up.
