### ISSUE TITLE
Constructing buildings

### ISSUE THREAD

**Issue by djsheehy** [simon987/Much-Assembly-Required#109]
This won't be easy but I think it's important. We need a use for all the copper, iron, and whatever other resources we might add to the game. Otherwise there's no point gathering them. Here's how my proposal will work.

1. Gather metal with the drill as usual.
2. Go to where you want to build.
3. Set register A to the BUILD action ID.
4. Set register B to the type of building you want.
5. After a number of ticks, (or instantly?) an unfinished building will appear.
6. Keep gathering materials and adding it to the building with the ADD_MATERIALS command.
7. Maybe there's a way to check how much material the building needs.
8. When it has enough materials, the building will appear.

**Comment by arthurpaulino** [comment]
i think that allowing players to build their own structures can lead to heavily polluted worlds. UNLESS the server has its own mechanics of corroding existing buildings. only maintained buildings would thrive against erosion. it would add a co-op feeling to the game experience.

**Comment by djsheehy** [comment]
I agree. I don't want permanent structures cluttering up the place.

**Comment by simon987** [comment]
Definitely a planned feature, but I want to implement this later on, after v1.4a. Some structures ideas would be:
- Battery (Store energy) 
- Solar panel (Outputs to adjacent batteries)
- Obstacle (blocks path), Rocket (#36)
- Nuclear Power Plant (Outputs to adjacent batteries, #38)
- Crusher (Suicide booth for user-controlled NPCs + trap -> crushes NPCs to get otherwise unobtainable item)
- Gate (Blocks path, open with comport or with special radio tower message)....

**Comment by djsheehy** [comment]
So you're going to have user code control multiple robots, like in [Screeps](http://www.screeps.com)?

**Comment by simon987** [comment]
It is a planned feature, yes.
