### ISSUE TITLE
GameUniverse is inefficient

### ISSUE THREAD

**Issue by djsheehy** [simon987/Much-Assembly-Required#121]
[The getWorld method of GameUniverse](https://github.com/simon987/Much-Assembly-Required/blob/master/Server/src/main/java/net/simon987/server/game/GameUniverse.java#L39) looks up a world by x and y coordinates by going through every world in a list and checking each one. If you have a lot of worlds, this might get slow. Instead you should have a HashTable with coordinates as keys:
```java
private HashTable<Point, World> worldsByCoordinates;
```
Then you can look them up much more efficiently.

The getUser method does the same thing. It should have a HashTable too to look them up by name.

**Comment by djsheehy** [comment]
The getUser method does the same thing. It should have a HashTable too to look them up by name.

**Comment by sg495** [comment]
Good point. Pull request #118 already switches worlds to ```private Hashtable<String,World> worlds```, because worlds are now identified in the database by a unique string ID (which can be computed as a function of the coordinates). Next pull request I make on database stuff I will also switch users to ```private Hashtable<String,User> users``` and update the `getUser` method accordingly.
