### ISSUE TITLE
Glitches in 8000,8000

### ISSUE THREAD

**Issue by DBJ314** [simon987/Much-Assembly-Required#125]
As of this moment, scrolling and general gameplay is really slow in the location of 8000,8000 but not elsewhere. There is a lot of biomass in the tiles that border other worlds (I harvested 14 seperate units of biomass from 1 tile). The wiki says that this can't happen.

**Comment by simon987** [comment]
I'm going to bed right now but I'm writing this down before I forget:
Getting this message from console: `Expected color but found ‘0’.` (from DOM) every tick. This is probably not related.
This is possible that a tile contains a lot of Biomass since NPCs will drop 8 blobs when dying.

What I suspect is some kind of deadlock with the NPCs because they can't get the path to the nearest blob (because they are sitting on it) and they stand there until they de-spawn, which creates more biomass and continues the cycle.
Right now biomass can't spawn on the border of Worlds (to prevent weird behavior like this) but it can be spawned by NPCs on death (and that probably needs to be changed).

If someone could go there and wipe all NPCs and collect all biomass I think it would stop the lag.

**Comment by DBJ314** [comment]
My robot is currently in 8001 7fff dealing with another one of these problems. The biomass collection counter is up to 0x400 and counting for a single tile. Not sure if I believe it.

I suggest that you have a maximum of 1 game object for each type of item on a tile and have that object store the number of items there. Instead of many lag inducing objects you will have 1 object with a large item count.

**Comment by arthurpaulino** [comment]
confirmed. my cubot is at `(7ff8, 8001)` feeding off of an infinite biomass glob. :smile:

**Comment by DBJ314** [comment]
(8002 , 8003) still has biomass around the edges and a NPC stuck in it. It isn't laggy, so it is either newly formed or a remnant from before you fixed the issue.

**Comment by simon987** [comment]
I didn't restart the server yet so the fix didn't apply. I might have to wipe the biomass blobs too, I didn't take the time to investigate the issue yet (My commit message was "Should fix #125" but I didn't realise github would close the issue as a result)
