### ISSUE TITLE
Track-seeking time

### ISSUE THREAD

**Issue by sg495** [simon987/Much-Assembly-Required#129]
Currently, the [Hardware: Floppy Drive](https://github.com/simon987/Much-Assembly-Required/wiki/Hardware:-Floppy-Drive) wiki page states that floppy read/write operations add 2ms to execution time:

>*Seek time is added to the total execution time, which is not yet calculated as of v1.3a

Also, there is a planned 20ms cap on the maximum execution time, as stated in the [CPU](https://github.com/simon987/Much-Assembly-Required/wiki/CPU) wiki page.

At present, this is not an issue, because the time limit is not as-of-yet enforced. But when it will be enforced, it will make any non-trivial floppy operation very complicated: with a maximum of 8-9 floppy operations possible per-tick, even a full memory dump would take 15-16 ticks to complete (not to mention that the code gets a little more complicated as well).

**Comment by DBJ314** [comment]
Maybe there could be a fast seek operation which takes energy instead of time. I have no idea if that is possible.

Another option could be a DMA controller. You give the floppy a list of sectors and memory locations, and it takes care of the rest. It could then set a memory location when it is done or maybe its status can be polled with a HWI. It doesn't even have to be built in hardware. Someone could just publish a code snippet that desribes the standard way of doing it.

**Comment by simon987** [comment]
The 2ms seek time would effectively add 2kJ to execution cost, without costing an actual 2ms of "real" execution time, since the 20ms limit is only there to allow more players code to be executed in the same tick. This is a bit confusing and maybe it could be explicitly written in the wiki that the cost of writing is 1kJ + seek time.

**Comment by sg495** [comment]
> The 2ms seek time would effectively add 2kJ to execution cost, without costing an actual 2ms of "real" execution time

Are you imagining this as the cubot idling while waiting for the floppy operation to complete? If so, turning 2ms into 2kJ makes sense.

>  the 20ms limit is only there to allow more players code to be executed in the same tick

Is it really necessary to have such an upper bound though? After all, the java implementation of the floppy read/write operations is rather efficient, so even allowing 30,000 floppy operations per tick will probably not break the bank (when compared to the 960,000 CPU instructions already allowed). 

Thus said, I think it makes sense to implement a more realistic bound on the number of operations that can be performed within a tick (1 second), perhaps based on real-world architectures from the 80s. I'll open a new issue about that and close this one.
