### ISSUE TITLE
Realistic execution/access times.

### ISSUE THREAD

**Issue by sg495** [simon987/Much-Assembly-Required#130]
As things stand, there is a 20ms maximum bound on the amount of real time that a cubot computation can take in a single tick, to ensure that server load is limited. Compared to the 1s of time that each tick takes, this seems unrealistically restrictive, especially if floppy-disk access times have to be included in the computation.

I propose to replace the 20ms _real time_ restriction with a 1s _simulated time_ restriction, assuming that cubots run on real x86-16 era hardware rather than modern hardware. For example, a cubot CPU with the performance equivalent of an early 5MHz Intel 286 would do 1MIPS, which is roughly the same as the current upper bound of 960'000 instructions per tick.

In this new setup, every instruction would take 1μs of _simulated time_, every floppy access (read/write) would take 20ms of _simulated time_, and each cubot would have 1s of simulated time available per tick (1,000,000 instructions or 50 floppy accesses). The server load in terms of _real time_ would be unchanged.

**Comment by simon987** [comment]
> The server load in terms of real time would be unchanged.

Problem is that some instructions, like using the Laser or the ComPort, while relatively inexpensive, takes a lot more execution time than a MOV instruction, for example. Another example is when an invalid instruction is executed, something like `MOV, 1, A`, a debug message is displayed on the console. Some other instructions/hardware also log some debug messages, which takes some execution time and would be very hard to set a specific simulated time for each one of these cases.

By the way, there is a 2ms seek time for floppy drives only if the previous read/write was not in the same sector. There are 80 sectors so you could read the entire floppy and have only 80 * 2ms seek time. 

The 2ms seek time could be reworded to 2kJ seek cost for clarity, as it was never intended to add this time to the real execution time.

I'd prefer to keep things simple by relying energy costs instead of having to deal with time costs. Realistically, the execution time never exceeds 1ms for the vast majority of players. The goal of the execution time limit is to avoid infinite loops taking all the server execution time.

**Comment by sg495** [comment]
> Another example is when an invalid instruction is executed, something like MOV, 1, A, a debug message is displayed on the console. 
> Some other instructions/hardware also log some debug messages
> would be very hard to set a specific simulated time for each one of these cases.

That won't be the case in a final, scalable version. Also, those things don't actually happen on the cubot, so you wouldn't associated any simulated time to them.

> Problem is that some instructions, like using the Laser or the ComPort, while relatively inexpensive, takes a lot more execution time than a MOV instruction

Couldn't you just reflect this in terms of simulated time that it takes to perform them?

>  I'd prefer to keep things simple by relying energy costs instead of having to deal with time costs. Realistically, the execution time never exceeds 1ms for the vast majority of players. The goal of the execution time limit is to avoid infinite loops taking all the server execution time.

I think having a simulated time framework makes things only marginally more complicated on implementation side (almost none at all, in fact), and probably won't have any effect on performance. But it would make the entire thing feel a LOT more realistic, and it would allow people to use more real-world intuition when programming advanced behaviour.

**Comment by simon987** [comment]
Realistic isn't what I'm aiming for and is a bit awkward for the tick-based system. What we're effectively doing by putting work on realistic execution time is that we're adding another variable that the players have to optimize instead of only having to worry about energy costs. 
I'd prefer the more casual approach, especially since we're mostly dealing with beginners. 

What I could do is to put an _energy_ cost for each instruction which could be based on it's real-world execution cost. I really don't want to mix up execution time (real and simulated) with energy cost. The problem with is that benchmarking the cost of individual actions is quite a lot of work, that is why I went with a real execution time cap.
