### ISSUE TITLE
Support for octal literal integers

### ISSUE THREAD

**Issue by kevinramharak** [simon987/Much-Assembly-Required#166]
Would be nice to have notation like:
```asm
octal: 0o777
;; some languages also allow a prefixed 0
octal: 0777
;; tough the capital O is just ugly
octal: 0O777
;; and unreadable
```
This depends on what is preferred notation

**Comment by Francessco121** [comment]
Looks like the game actually supports this already in the format of `0777` (from your example). The game parses integers with [Integer.decode](https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#decode(java.lang.String)) ([here's the MAR source](https://github.com/simon987/Much-Assembly-Required/blob/master/Server/src/main/java/net/simon987/server/assembly/Assembler.java#L169)). Because of this method, the game inherits some other funky ways of writing integers (like `#` before a hexadecimal number, which assembles even though the game's editor shows an error).

That said, I would definitely prefer using the `0o` prefix if the game supports it.
