### ISSUE TITLE
Keep backups of saved files

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#8]
Keep a certain number of backup save files. When the game is saved, the previous save file should be moved to a directory, or (ideally) compressed in a Zip file instead of being overwritten.

**Comment by StevenBerdak** [comment]
You can go ahead and assign this to me. Just going to add a check to see if file exists and store previous copies to an archive.

**Comment by simon987** [comment]
@StevenBerdak Okay, it would be nice to limit the size of the archive too, if you can

**Comment by StevenBerdak** [comment]
I'm still working through this issue. There are actually a few constraints that aren't immediately obvious. Putting together a nice clean system for managing a zipped archive using  core java.

**Comment by StevenBerdak** [comment]
I have a fairly robust implementation. It is basically completed I just have to work out a few minor things.  I can submit the pull request tomorrow and the you are free to look it over and suggest changes or whatever. 
Essentially it stores a list of files in an array and once the program exits it dumps them to a new zip file. It also pulls and previous zips from the previously saved file when the program loads.
There are a few bugs and design issues that need to be hammered out but the core functionality works great.

**Comment by StevenBerdak** [comment]
The main issue here is that you cannot add files to a physical zipfile once it has been put on the drive and encoded. So therefore you would have to save a new zipfile every time which means more encoding every time you want to save. When I tested a similar Model I noticed a 3% CPU load which is not extreme but I am on a higher-end desktop. The other issue with that is that that means file deletion otherwise your storage folder is going to get overloaded. So I single file per zip would make sense assuming that the compression is high enough to make it worth it. I will try to make the ideal case of a single save archive, however there would probably be a parameter and place to establish how many saves Cycles to iterate it before saving off the zipfile again to have more control over a cpu intensive task. 
Maybe I am over thinking this. Ill have time to sit down and work on this tomorrow. Already have methods written I just need to put everything together.
